/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface UtilsInterface extends utils.Interface {
  contractName: "Utils";
  functions: {
    "uint2hex64str(uint256,uint8)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "uint2hex64str",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "uint2hex64str",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Utils extends BaseContract {
  contractName: "Utils";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UtilsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    uint2hex64str(
      i: BigNumberish,
      ml: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  uint2hex64str(
    i: BigNumberish,
    ml: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    uint2hex64str(
      i: BigNumberish,
      ml: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    uint2hex64str(
      i: BigNumberish,
      ml: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    uint2hex64str(
      i: BigNumberish,
      ml: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
